// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkgdlrhdrkpptlakllbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ2RscmhkcmtwcHRsYWtsbGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mjc2NDksImV4cCI6MjA2OTAwMzY0OX0.mS1hq7qsB0NiAvg8g-DNtYZZpVlhEwprMd36B3D0wOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});